<meta charset="utf-8">
<script>

    const i = 1;

    const case_value = 4

    /*回调函数原理实参传形参函数顺序执行-----------------------------------------------------*/

    switch (case_value) {

        case 1:

        function f(callback) {
            if (i > 0) {
                setTimeout(() => {
                    console.log('callback前运行')
                    callback(i)
                    console.log('callback后运行')
                }, 1000)

            } else {
                throw  new Error('err')
            }
        }

            try {
                f(function (i) {
                    console.log('callback返回值')
                })
            } catch (err) {
                console.log(err)
            }
            break
        case 2:
            /*promise-原理promise对象传递数据,then.catch接收---------------------------------------------------*/

            new Promise((resolve, reject) => {
                if (i > 0) {
                    setTimeout(() => {
                        resolve('promise返回值')
                    }, 2000)
                } else {
                    reject(new Error('err'))
                }

            }).then(
                res => console.log(res),
            ).catch(err => console.log(err))

            break

        case 3:

            /*promise await原理promise对象传递数据,async await接收----------------------------------------------------*/
        function f3() {
            return new Promise((resolve, reject) => {
                if (i > 0) {
                    setTimeout(() => {
                        resolve('promise返回值')
                    }, 1000)
                } else {
                    reject(new Error('err'))
                }

            })
        }


        async function f4() {

            try {
                console.log('这句不异步')
                const res = await f3()
                console.log(res)
                console.log('这句异步')
            } catch (err) {
                console.log(err)
            }
            console.log('这句也异步,只是没有捕捉错误')
        }

            f4()
            break


        /*async await----------------------------------------------------*/
        case 4:

        async function f1() {

            if (i > 0) {
                return 'asyncFn返回值'
            } else {
                throw new Error('err')
            }
        }

        async function f2() {

            try {
                console.log('这句不异步')
                const res = await f1()
                console.log(res)
                console.log('这句异步')
            } catch (err) {
                console.log(err)
            }
            console.log('这句也异步,只是没有捕捉错误')
        }

            f2()

    }
</script>


