<meta charset="utf-8">
<script>

  const i = true;

  const case_value =4

  /*回调函数原理实参传形参函数顺序执行-----------------------------------------------------*/

  switch (case_value) {

    case 1:

    function f1(callback) {
      if (i) {
        setTimeout(() => {
          console.log('callback前运行')
          callback(i)
          console.log('callback后运行')
        }, 1000)

      } else {
        throw  new Error('err')
      }
    }
      try {
        f1(function (i) {
          console.log(i)
        })
      } catch (err) {
        console.log(err)
      }
      break
    case 2:
      /*promise-then---------------------------------------------------*/

      new Promise((resolve, reject) => {
        if (i) {
          setTimeout(() => {
            resolve('promise返回值')
          }, 2000)
        } else {
          reject(new Error('err'))
        }

      }).then(
        res => console.log(res),
      ).catch(err => console.log(err))

      break

    case 3:

      /*promise asyncawait----------------------------------------------------*/
    function f3() {
      return new Promise((resolve, reject) => {
        if (i) {
          setTimeout(() => {
            resolve('promise返回值')
          }, 1000)
        } else {
          reject(new Error('err'))
        }

      })
    }


    async function f3_() {

      try {
        console.log('这句不异步')
        const res = await f3()
        console.log(res)
        console.log('这句异步')
      } catch (err) {
        console.log(err)
      }
      console.log('这句也异步,只是没有捕捉错误')
    }

      f3_()
      break


    /*async await----------------------------------------------------*/
    case 4:

    async function f4() {

      if (i) {
        return 'asyncFn返回值'
      } else {
        throw new Error('err')
      }
    }

    async function f4_() {

      try {
        console.log('这句不异步')
        const res = await f4()
        console.log(res)
        console.log('这句异步')
      } catch (err) {
        console.log(err)
      }
      console.log('这句也异步,只是没有捕捉错误')
    }

      f4_()
      break
    /*async().then----------------------------------------------------*/
    case 5:

    async function f5() {

      if (i) {
        return 'asyncFn返回值'
      } else {
        throw new Error('err')
      }
    }

      f5().then(res =>
        console.log(res)
      ).catch(err =>
        console.log(err))
      break
  }
</script>


